# fly.toml app configuration file generated for usedconex-webhook-yourid on 2025-08-15T02:16:57+03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'usedconex-webhook-yourid'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = '15s'
    timeout = '3s'
    grace_period = '20s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 3000
  path = '/healthz'
